### ISSUE TITLE
Add Brave Details

### ISSUE THREAD

**Issue by pes10k** [cookie-status/cookie-status-dev#1]
I saw the call for Brave comments on there.  Happy to help / add information about what we do.  Whats the best way to help?

**Comment by sahava** [comment]
Thank you so much!

I think the first thing would be to populate a column for it in the Current Status table, similar to how the other browsers have right now. So:

* What the tracking protection mechanism is called (if anything), e.g. "Intelligent Tracking Prevention" for WebKit
* Which version (with link to release notes) is the latest version of this mechanism deployed in
* Link to the latest release of the browser
* What is the default protection mode called (e.g. "Balanced" in Edge)
* How are "known trackers" classified (e.g. "Disconnect.me" for Firefox), link to list if a public list is used
* How does tracking protection impact cookies in 3P context
* How does tracking protection impact cookies in 1P context
* How is other browser storage (localStorage, sessionStorage, IndexedDB) impacted in 3P context
* How is other browser storage (same) impacted in 1P context
* What is the default referrer policy & is there other impact on referrer from a tracking protection point of view

If there are upcoming patches or releases around tracking protection, then links to their release notes or buglogs for the "Bubbling under" section.

I've got Brave finally running on my computer as well, so will happily contribute as well. Thanks again!

**Comment by fmarier** [comment]
Here's what the Brave entry should look like:
- **Mechanism**: Shields
- **Deployed in**: 0.55.18
- **Latest release**: https://brave.com/latest/
- **Classification of "known trackers"**: n/a (storage restrictions apply to all origins)
- **Cookies in 3rd party context**: Access restricted to all
- **Cookies in 1st party context**: For cookies set with document.cookie, expiration set to a maximum of 7 days. Other cookies have a maximum expiry of 6 months.
- **Other browser storage in 3rd party context**: No restrictions
- **Other browser storage in 1st party context**: No restrictions
- **Referrer**: cross-origin referrers are spoofed or stripped

**Comment by pes10k** [comment]
Some follow ups, just to clarify some places where we weren't sure exactly what was being asked for:

Brave blocks or modifies a large number of requests, based on rules taken from EasyList, EasyPrivacy, Disconnect, uBlock Origin and generated internally (https://github.com/brave/adblock-rust/blob/master/src/filter_lists/default.rs).  Since we block these requests completely, we don't directly base storage on them, but have the downstream effect of blocking storage (and everything else) from any advertisers or trackers labeled by these lists.

**Comment by pes10k** [comment]
Also, now that 1.0 is out, we also plan to match Safari's restrictions on the lifetime of JS set storage (https://github.com/brave/brave-browser/issues/4438)

**Comment by sahava** [comment]
Thank you!

#10
