### ISSUE TITLE
Consider changing the font to make things more readable on Windows

### ISSUE THREAD

**Issue by jakub-g** [cookie-status/cookie-status-dev#16]
In Chrome on Windows, the font renders as follows for me (click the image to see real-size picture):

![image](https://user-images.githubusercontent.com/1437027/70897445-f0293300-1ff2-11ea-8645-20fd3157ec99.png)
(in Firefox just only a little bit better)

Very thin fonts in general are rendered bad on Windows in my experience. It's a common issue with websites designed on a Mac with retina screen.

**Comment by sahava** [comment]
Thank you! General visual updates for readability and accessibility are definitely on the radar.

**Comment by sahava** [comment]
Updated to Helvetica, weight 400. Thanks!

efd179e2db3c78b61fe86b2f7c941223ffa321f8
