### ISSUE TITLE
Make latest ITP 3rd-party cookie blocking status clearer

### ISSUE THREAD

**Issue by abebis** [cookie-status/cookie-status-dev#20]
The Current status of "Cookies in 3rd party context" for Safari is:

> Access restricted if no prior interaction in first-party context.

It is not clear if "interaction in first-party context" refers to interactions with "the domain being visited" or "the cookie's domain". 
What about changing it to something like

"Access restricted if no prior interaction with the first-party domain" 

"first-party domain" being the domain of the "website that has its URL shown in the URL bar" as
explained [here](https://twitter.com/johnwilander/status/1207032119546929152).

It could also be mentioned here that cookies from domains (even tracker domains if they got prior user interaction) can be accessed using the Storage Access API.

**Comment by sahava** [comment]
Thank you, you're right - it was too ambiguous. I have fixed this in 542e31c683ac51be5e4156d2652ebb8b052c7e87.

Storage Access API is something that will fall under Safari's own section in the site - I haven't yet figured out whether to add user / site controls to the Current Status page - I want to avoid information overload. But this is certainly on the backburner.
