### ISSUE TITLE
[Bubbling under] Bring back "Block all third-party cookies" feature for Safari

### ISSUE THREAD

**Issue by abebis** [cookie-status/cookie-status-dev#22]
The "bubbling under" feature "Block all third-party cookies, regardless of prior access" was removed in #14 (probably in response to the latest ITP update), even though it has not been released yet.
https://twitter.com/LucasExqDit/status/1207452502574215169
It is still an experimental feature (off by default) in Safari TP97 and WebKit trunk, called "Block All 3rd-Party Cookies (ITP)"

https://trac.webkit.org/changeset/252840/webkit
> The reason for supporting three different modes is that what is now named OnlyAccordingToPerDomainPolicy is shipping, AllOnSitesWithoutUserInteraction is
in beta, and All is behind an experimental flag.

"AllOnSitesWithoutUserInteraction" is the one released on December 10.

**Comment by sahava** [comment]
Fixed in #23 - thanks!
