### ISSUE TITLE
Safari Tracking details

### ISSUE THREAD

**Issue by yokoffing** [cookie-status/cookie-status-dev#26]
Safari 14 has a tracker blocking. So the Safari section needs to be updated.

You are probably already aware of this. However, I mostly wanted to submit this URL https://webkit.org/tracking-prevention/ that now maintains a running list of all tracking prevention measures Safari uses.

**Comment by sahava** [comment]
Thanks - Safari 14 didn't introduce any changes to ITP itself - 3P cookie blocking was already added to ITP (and pre-14 versions of Safari).

Safari 14 introduced the Privacy Report, which certainly deserves a footnote in the Safari section of the site.

The link to WebKit's tracking preventions is a good idea - I'll make sure to add it.

With Safari 14, esp. iOS/iPadOS, I think we need a "mobile" section for the browsers.

**Comment by yokoffing** [comment]
Right — Privacy Report was introduced in 14, not any changes to ITP. Sorry for not being more specific!

**Comment by sahava** [comment]
Added note about iOS browsers in https://github.com/cookie-status/cookie-status-dev/commit/d069b3447327d68943e16e84356af2cacb1847f2
