### ISSUE TITLE
Add Chrome 83 Incognito window 3P cookie blocking

### ISSUE THREAD

**Issue by sahava** [cookie-status/cookie-status-dev#27]
Since it's opt-in, it should go under Chrome's own section.

**Comment by sahava** [comment]
Actually, no. The purpose of the site isn't to explore all the opt-in privacy options as well, as they require the user to take manual steps to enable. CookieStatus.com should focus on the default settings alone.

**Comment by jakub-g** [comment]
AFAICT it's not opt-in, it's enabled by default in incognito tabs

![image](https://user-images.githubusercontent.com/1437027/89538194-8ddba780-d7fa-11ea-92fb-f81cf7ba4bad.png)

**Comment by sahava** [comment]
It *is* opt-in. To opt-in, you need to open an Incognito tab. The only way it wouldn't be opt-in is if Chrome opened *by default* in Incognito mode.

It's opt-in privacy, just like Firefox' Private Windows is, or any browser extension that you need to download and enable for the privacy settings to kick in.

As mentioned in this and other issues, for now Cookie Status is concerned with *default* privacy modes, which is the tracking protection the user is privileged to when opening a browser instance. I'm not against adding sections for opt-in privacy modes as well, but it's not a priority. Anyone is of course free to submit suggestions for how opt-in modes are explored in Cookie Status.
