### ISSUE TITLE
Consistent terminology

### ISSUE THREAD

**Issue by sahava** [cookie-status/cookie-status-dev#3]
From John Wilander:

"...one thing that may show your perspective and be perceived as an “agenda” is that you call it restrictions rather than protections. The intention of all these restrictions is protection of user privacy."

To-do: Style guide, consistent terminology, avoid bias.

**Comment by rvidakovic** [comment]
One could argue that tracking 'protection' is just as biased. A more neutral term would be 'prevention'.

**Comment by sahava** [comment]
Regardless of terminology choice, there's bound to be either bias or ambiguity (or both). I'll put this issue on the back-burner - I don't think it's a priority in any way; I might update the statement in the fact ("There's no agenda...") to be a bit more realistic in terms of the semantic repercussions of stating something like that.
