### ISSUE TITLE
Firefox 79

### ISSUE THREAD

**Issue by yokoffing** [cookie-status/cookie-status-dev#30]
Firefox 79 includes ETP updates: "The new release includes version 2 of Enhanced Tracking Protection (ETP) which now automatically protects people from unwanted first-party cookies." This is done by their use of Disconnect lists. See https://wiki.mozilla.org/Firefox/Roadmap/Updates#2020-07-27:~:text=The%20new%20release%20includes%20version%202,protects%20people%20from%20unwanted%20first%2Dparty%20cookies.

I'm not sure if this is related to `privacy.trackingprotection.enabled` or to `privacy.purge_trackers.enabled`. I can't find any documentation to clarify.

Commentary: If it's the former, it is useless to me. I only leave Firefox's tracking protection [enabled for Private Browsing](https://github.com/yokoffing/Better-Fox/blob/535d992791749f26588801c25febac4ae7907a69/SecureFox.js#L22-L23). I let my [DNS server and content blocker handle normal browsing](https://github.com/yokoffing/Better-Fox/blob/535d992791749f26588801c25febac4ae7907a69/SecureFox.js#L25-L30).

**Comment by sahava** [comment]
Thanks! Yeah - I'm waiting for clarification on just how this works before adding it to the site. Hopefully the stable channel release notes are updated accordingly.

**Comment by sahava** [comment]
Added in 49960ad43e8b5da3167b5a22e4cf6d475692039f

Thanks!

**Comment by yokoffing** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Redirect_tracking_protection

Hi! I was going to send you this link so you can add additional information, but it appears you found it as well. Cheers!
