### ISSUE TITLE
[Content issue] /chrome/_index.md

### ISSUE THREAD

**Issue by invi2000** [cookie-status/cookie-status-dev#33]
I think this is no longer correct:

> Third-party cookies
> Chrome does not restrict the use of third-party cookies.

As far as I know 3rd party cookies are now blocked by default or at least in incognito windows.
https://www.labnol.org/enable-third-party-cookies-in-google-chrome-14986

**Comment by sahava** [comment]
As noted here: https://github.com/cookie-status/cookie-status-dev/issues/29 - Incognito mode is not a default browser mode. It's opt-in - the user must enter Incognito mode to have the privilege of tracking protections. For now, this resource is about the *default* tracking protections of web browsers - the ones that apply with a fresh install without any browser extensions.
