### ISSUE TITLE
Brave CNAME cloaking protection

### ISSUE THREAD

**Issue by antonok-edm** [cookie-status/cookie-status-dev#35]
The `CNAME cloaking` section for Brave is outdated - CNAME adblocking made it into the release channel as of version 1.17 last month. It looks like Brave's relevant blog post announcement is already linked in the `Bubbling under` section, but let me know if any additional information is needed.

**Comment by sahava** [comment]
Thank you - yes, I actually had a reminder to update this mid-November when the update rolled out, but paternity leave got in the way.

**Comment by sahava** [comment]
Updated in 5621409c9716c213e68f8332c98e27654995cdfb - thanks again @antonok-edm!
