### ISSUE TITLE
[Content issue] /brave/_index.md

### ISSUE THREAD

**Issue by pes10k** [cookie-status/cookie-status-dev#37]
Thank you again for this great resource!  Just wanted to note that Brave's 3p storage policy has changed, and is currently being rolled out to Stable (should be fully rolled out by EOD on March 12, 2021).  The new policy is described here: https://brave.com/privacy-updates-7 , but the short of it is that 3p storage will be ephemeral for all sites (i.e. 3p storage keyed under a site is cleared whenever the last top level document pointing at the site is closed).

Hope that helps and again, thanks much for the terrific resource!

**Comment by sahava** [comment]
Thank you so much, I've updated this in https://github.com/cookie-status/cookie-status-dev/commit/1075de66dd0246261ce005001a68b1094f813a99

**Comment by pes10k** [comment]
Thank you!
