### ISSUE TITLE
Firefox: Total Cookie Protection

### ISSUE THREAD

**Issue by SonicMike** [cookie-status/cookie-status-dev#40]
The section on Firefox should be updated to mention a new change.  Total Cookie Protection  - https://blog.mozilla.org/en/products/firefox/firefox-rolls-out-total-cookie-protection-by-default-to-all-users-worldwide/

**Comment by sahava** [comment]
Thanks – addressed in https://github.com/cookie-status/cookie-status-dev/commit/ed8c67c4bdf29fdf5924b23484c6cd73fd958856
