### ISSUE TITLE
[Content issue] Current Status - Chrome 104 limits cookie expiry to 400 days

### ISSUE THREAD

**Issue by covik** [cookie-status/cookie-status-dev#42]
Since Chrome version 104 you cannot set cookie expiration longer than 400 days (actually you can but they are adjusted down to 400 days).
More information here: https://support.google.com/chrome/a/answer/7679408#cookieExpDate104

**Comment by sahava** [comment]
Thanks! Fixed in a9acdc86fa002c886c8f8eb25590bd9f8b4ed617
