### ISSUE TITLE
Safari 16.1+ sessionStorage partitioning

### ISSUE THREAD

**Issue by WestonThayer** [cookie-status/cookie-status-dev#44]
Latest Safari versions now partition `sessionStorage`. I can’t find release notes or official documentation for this change, but discovered via https://github.com/firebase/firebase-js-sdk/issues/6716.

**Comment by sahava** [comment]
Thank you, updated in [475b89c](https://github.com/cookie-status/cookie-status-dev/commit/475b89c175695e78a4794a7f7dc57c5b7a168834)
