### ISSUE TITLE
Make table header cells sticky

### ISSUE THREAD

**Issue by simevidas** [cookie-status/cookie-status-dev#50]
```css
th {
  position: sticky;
  top: 0;
}
```

Additionally, you’ll need to remove `overflow: auto` from the ancestor `#cs` and `.highlightable` `<div>` elements, which will disable horizontal scrolling for the table at narrow viewport widths. This is a limitation of CSS. You can’t have a table with sticky headers and horizontal scrolling at the same time. However, you could add JavaScript code that checks if the table fits horizontally into the viewport and remove `overflow: auto` only then.

https://github.com/user-attachments/assets/29e76789-5cf5-4cfb-babe-08d1d4ff77bb

**Comment by sahava** [comment]
Thanks – fixed in 3bc64aa. I opted to just make the change without checking for table width. It works on mobile just fine, but the table does extend past the horizontal boundary of the content.
