### ISSUE TITLE
Chrome now uses partitioning for iframes storage, same as Safari

### ISSUE THREAD

**Issue by remorses** [cookie-status/cookie-status-dev#51]
https://developers.google.com/privacy-sandbox/cookies/storage-partitioning?hl=en

**Comment by luukfiets** [comment]
@sahava,

I noticed the same as @remorses. It seems that recent updates to the browser are not reflected on the home page, nor on the browser detail pages. Chrome enabled storage partitioning for all users in version 115, released in July 2023. 

Are there any plans to update the website? Will PRs be reviewed?

**Comment by sahava** [comment]
Fixed in 01503c4, thank you.
